### ISSUE TITLE
Show Document Kind for .zing files as "Zing File" in Finder

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#109]
Currently Zing files show up as com.zingworkshop.zing. It would be better if it showed as "Zing File" or maybe "Zing Source"

![screen shot 2017-06-01 at 13 31 07](https://cloud.githubusercontent.com/assets/8209164/26663565/f36eb7ec-46ce-11e7-8c81-5dc7a5a48cd8.png)

**Comment by aaronkennedy** [comment]
Shows as Zing document for me
