### ISSUE TITLE
Having to reload screen twice when dynamic data is involved

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#140]
Trying to load data from JSON files and attache elements dynamically. The first time the screen loads no data is show. The second time I enter the screen the data I expect is show.

**Comment by aaronkennedy** [comment]
Loading a JSON file is asynchronous in Zing. However, the second time you load it the data is already available so it appears to be synchronous. You need to structure your code to wait for the load to complete before you create your elements.
