### ISSUE TITLE
Unable to diagnose why 'The preview was halted as it had not responded for 500ms'

### ISSUE THREAD

**Issue by NigelBreslaw** [ZingWorkshop/Studio#183]
In version 'a6101212e72371547af59d3dac47f26b5b7e81b6' of Ishtar I often get 
Zing Backtrace:
    1  /Users/breslaw/Commander/ishtar2/app/Data.zing:67:9 
    2  /Users/breslaw/Commander/ishtar2/app/Data.zing:18:42 
    3  /Users/breslaw/Commander/ishtar2/app/Logic.CharacterCreation.zing:21:9 
    4  /Users/breslaw/Commander/ishtar2/app/Logic.NetPlatform.zing:95:21 
    5  /Users/breslaw/Commander/ishtar2/app/Logic.NetPlatform.zing:311:9
The preview was halted as it had not responded for 500ms

But I don't know how to diagnose why it is halting sometimes and not others.

**Comment by NigelBreslaw** [comment]
If it makes any difference quitting ZingStudio stops this happening with the simulator. Then after it has restarted many many times the issue comes back.

**Comment by aaronkennedy** [comment]
I'm 95% sure this has nothing to do with the number of restarts. Classic Morty-level false correlation.
