### ISSUE TITLE
Effect.MaskImage needs status like Image has

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#217]
The Effect.MaskImage needs statuses so that there is no flash of an unmasked element. I'm using masks for some icons an as it initially loads I see a rectangle of solid color.

**Comment by custa1200** [comment]
Will it just wait till the masking image is shown before whowing what is to be masked or will there be loading states of the mask?

**Comment by aaronkennedy** [comment]
Currently there is just a status property on Effect.MaskImage. it would make sense to also have a behaviour property to control what it does while the mask is loading, but that's another bug ;)
