### ISSUE TITLE
Extend log 

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#285]
Currently the log in Zing is limited to 200 entries... it would be useful if this was either unlimited or a much higher limit like 5,000.

**Comment by gforce** [comment]
Yup. A longer log would be great

**Comment by michaelahokas** [comment]
This would be pretty handy right now as I'm printing out lots of timestamps from a program guide... there are a lot more than 200 of them.

**Comment by gforce** [comment]
Michael, it’s pretty easy to get Loggly working with Zing, if you need more substantial logging.

**Comment by PanzeriT** [comment]
To have a filter in the log window would be nice as well. Currently it's a bit hard to find the right place in the logs, especially if the logs are getting bigger.
