### ISSUE TITLE
Aaron will buy Michael a retina display for home

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#328]
... so he stops getting these kinds of bug reports.

On a non-retina display at 70% zoom the following issue was observed
![screenshot 2018-08-10 21 10 52](https://user-images.githubusercontent.com/8209164/43955158-4affb604-9ce2-11e8-9e97-4a646abbf0c5.png)

**Comment by aaronkennedy** [comment]
Bad news, it can be fixed in software.
