### ISSUE TITLE
Lost Project After Zing Crash

### ISSUE THREAD

**Issue by ekloss5156** [ZingWorkshop/Studio#333]
Learning the product and had frequent crashes, followed directions to reset and now I have to access to the work, I was working late to have for work tomorrow.  Project said unsupported below but was not an issue at all until the crashing.  Also now have this error log that states the file failed to load, please advise how to recover as I have spent much time to attempt to teach myself this skill for it to disappear.

Thanks,

Eric

**Comment by aaronkennedy** [comment]
Sorry to hear you're having problems. Can you email hello@zingworkshop.com with a screenshot of what is happening and a copy of the error log you refer to? Zing projects are just a collection of text files, so we should be able to figure out what is going on pretty quickly.

I'll close this bug, and we can continue to track down the problem over email!
