### ISSUE TITLE
Color picker doesn't work correctly on multiple displays

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#374]
If Zing Studio is on a retina display, the color picker is offset by quite a lot so it's very hard to use... if you move the studio window onto a non-retina display it works perfectly.

<img width="189" alt="screenshot 2018-10-27 20 10 59" src="https://user-images.githubusercontent.com/8209164/47602059-ecb89e00-da24-11e8-9548-095170438376.png">

**Comment by aaronkennedy** [comment]
I can't reproduce this. What are the exact display sizes, layout and macos version?

**Comment by michaelahokas** [comment]
I can reproduce this at home and work... 
In both cases: MacBook Pro (15-inch, 2017) with macOS 10.14 (18A391) 

At home it's connected to a 27" Apple Thunderbolt display with the external display as the main display. Zing is running on the Mac display.

At work I arranged it so that an external 1920x1080p display was the main display and the zing studio window on the mac and the simulator on the external (1920x1080p) display... in this case I saw the following offset:
![screenshot 2018-10-29 11 07 55](https://user-images.githubusercontent.com/8209164/47624000-6064c300-db6b-11e8-8923-1dd1565101f5.png)

When I connected a 5K display and made it the main display i observed this offset
<img width="202" alt="screenshot 2018-10-29 11 12 53" src="https://user-images.githubusercontent.com/8209164/47624027-bdf90f80-db6b-11e8-9355-2c4dc87ca406.png">

You can see the color picker is magnifying her earring a long way below where it actually appears on screen.

The only way it works correctly is if The main studio window is on the main display.
