### ISSUE TITLE
It's not possible to drag zing files into a project

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#388]
It's probably not needed often, but it does seem weird that you can't drag a zing file into a zing project.

**Comment by aaronkennedy** [comment]
It's not really clear what it should do. Sometimes you would want it to copy the file, other times it should open the project with that file. And if it copies the file, should it also copy the states file that you *didn't* drag etc?

**Comment by custa1200** [comment]
@aaronkennedy is there a reason the States files are not included in the actual Zing file? Does it come down to it is just more potentially brittle with people editing files?

**Comment by aaronkennedy** [comment]
They’re not really human editable. They are technically zing files, but with lots of unfriendly int ids etc
