### ISSUE TITLE
Add support for re-ordering projects

### ISSUE THREAD

**Issue by gforce** [ZingWorkshop/Studio#415]
It would be useful to be able to drag-to-re-order projects on the LHS. I tend to have a few projects open at the same time, and switch b/t open projects a fair bit. It would be handy if the frequently switched projects could be positioned next to one another.

**Comment by gforce** [comment]
For now, I close the related projects and re-open them at the same time

**Comment by aaronkennedy** [comment]
Yes, this makes sense. Just incase you weren't aware of it, you can also switch between projects with the <Option + ~> shortcut

**Comment by gforce** [comment]
schweet!!
