### ISSUE TITLE
Sizing Apple controls

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#418]
Something I am working on at the moment is showing an apple toggle but in a smaller size(18dp high). is it possible to be able to scale the height of these apple controls. I have used a scale factory of 0.6 but then run into issues of whitespace around it.

**Comment by aaronkennedy** [comment]
Item {
    width: children[0].width * children[0].scale
    height: children[0].height * children[0].scale
    Apple.Switch {
        transformOrigin: .TopLeft
        scale: 0.6
    }
}
