### ISSUE TITLE
Fake keyboard in simulator/web runtime does not change the bottom safeArea

### ISSUE THREAD

**Issue by NigelBreslaw** [ZingWorkshop/Studio#471]
On an android phone the button moves above the real keyboard when shown. But does not move above the fake keyboard in the web runtime and the simulator 
https://www.zingstudio.io/share/safe/cd306fd41d1f4b833fbc56af34fc7523decb6814038ced4c417ffe315adb7290

**Comment by aaronkennedy** [comment]
This is now consistent across platforms.
