### ISSUE TITLE
Json Modeller Improvements

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#476]
Using the JSON modeller a bit and run into a number of issues with the current implementation when using 3rd party API I have no control of the structure over. Just thought I would open a ticket here and put in some things I believe could improve the experience. I can ad to this over time.

- [x] any time I change the name of a item after hitting return it scrolls the editor back to 0,0 which is frustrating

- [x] ability to create a datum that will allow me to select a object in the modeller and then be able to  choose its keys to add

- [ ] It would be great if I command click on a datum property like with element (green ones)  it would scroll to focus the item in the editor, which would be helpful on large models to navigate around
<img width="463" alt="Screen Shot 2019-05-22 at 10 50 46 am" src="https://user-images.githubusercontent.com/161224/58139961-84f7c800-7c80-11e9-9017-0401db2af598.png">

- [ ] Subsequently it would be great to control click on the datum header it would scroll to and  focus the place it is referenced

- [ ] Being able to lay them out and move them on the surface like the states editor would help with organisation

- [x] Get rid of underscores in the edited property name that may be generated if the JSON has underscores in keys

- [x] Ability to bulk clear all the design, or select and clear multiple selections

- [x] if a dot checked next a node in the Wizard view the Model view goes back to 0,0

- [x] it would be great if there was a bi-directional hover state what would show the item hovered on in the opposite Wizard or Model views

- [ ] the ability to model inside a JSON object that is being used as an array buy is not an array

 - [x] property types should be green like the rest of the IDE

- [x] play nice when the root object is an array

**Comment by gforce** [comment]
This one is by far the most frustrating, imo:
"any time I change the name of a item after hitting return it scrolls the editor back to 0,0 which is frustrating"

I rename a lot when setting up a new model
