### ISSUE TITLE
Select focused instance

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#482]
When using  Find (command-f) and selecting items in preview, you can jump to the element definition in the top right panel... the issue is that Zing selects the first instance of the element rather than the instances that is being clicked on. I have about 1500 instances of an element and it's hard work finding the one i'm looking at.

**Comment by aaronkennedy** [comment]
This shouldn't be the case. Can you provide a screenshot of the "top right panel" (presumably the Outline panel?) where jumping to the element fails.
