### ISSUE TITLE
Allow masking of Apple.BlurLayer

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#484]
I'm trying to recreate a popover but if i apply a mask to an Apple.BlurLayer the blurring is disabled.

    Apple.BlurLayer as shade {
        anchor bounds = menu.bounds
        stacking: 1
        style: .ExtraLight
        
        with Effect.MaskImage {
            source: "images/Examples/Content/Device menu background.png"
        }
    }

**Comment by aaronkennedy** [comment]
Can you provide a more complete code example? At least in the simple case - https://www.zingstudio.io/share/Bug_484/fd9481632ba08c56d528665c6495fc9bffd5fd56bc99aced3602722ff7e16048?live=1 - it works.

**Comment by michaelahokas** [comment]
I found the issue... the mask image didn't have 100% opacity
