### ISSUE TITLE
Add support for HTTP Patch

### ISSUE THREAD

**Issue by gforce** [ZingWorkshop/Studio#489]
I'm working with Firebase for user auth, persistence (Firestore) and some other malarkey. Update operations on both Firestore and RealtimeDB use the patch verb.

This one is a bit of a show stopper I'm afraid. I'm keen to stick with Firestore for persistence as their REST API is pretty decent and easy to hook into to, which makes Zing integration easy.

Plus, the alternatives aren't any better 
- AWS dynamo db is sdk based (they have an old, low level rest api but its meh)
- Microsoft Cosmos has a good REST API, but It uses PUT (yup..) to replace a document rather than being able to patch specific fields. That does not suit my use case. 

So adding patch support to Zing would be awesome.

**Comment by gforce** [comment]
In fairness, that last line is subjective ;-).

**Comment by aaronkennedy** [comment]
I'll add support for generic HTTP verbs

**Comment by gforce** [comment]
cool. thx
