### ISSUE TITLE
Select all children

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#491]
the JSON modeller could benefit from a Select all children next to an object. i.e. next to the 0 in the image it would select the 20 children rather than me selecting individually.

<img width="280" alt="Screen Shot 2019-07-12 at 11 34 48 am" src="https://user-images.githubusercontent.com/161224/61096006-48cf2f80-a499-11e9-99c6-b790cae04581.png">

**Comment by aaronkennedy** [comment]
This feels too niche to have a specific option
