### ISSUE TITLE
Preview app can prevent iPhone X from unlocking

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#495]
If you have preview in landscape mode and lock your phone. Then try to unlock it, you can't always swipe all the way up... it only slides up a little... enough to see maybe 50px of the bottom of the preview app and then it won't continue. I've seen it now at least 4-5 times but i can't seem to get it to happen every time.

**Comment by aaronkennedy** [comment]
I can't reproduce this
