### ISSUE TITLE
Color types in JSON/JSON5 files

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#500]
It would be great if types could be shown in the JSON files, i.e. Boolean, Strings, Floats, it would also be cool if colours could be interpreted/shown based on #00000000 values

**Comment by aaronkennedy** [comment]
What is the point of explicitly showing the type, as it is unambiguous given the value?

**Comment by custa1200** [comment]
an example of this is the way JSON is shown in VS Code. As you can see it makes items like floats and bools standout a little more clearly, having color shown would be helpful as well at a glance

<img width="490" alt="Screen Shot 2019-08-24 at 10 26 33 pm" src="https://user-images.githubusercontent.com/161224/63637409-1ed77280-c6bf-11e9-9855-35455a4214e3.png">
