### ISSUE TITLE
Zing does not render images on the Sony Experia M5

### ISSUE THREAD

**Issue by NigelBreslaw** [ZingWorkshop/Studio#51]
This device and also one of the Asus Zenphones renders rectangles and fonts fine. But no images. See attached 
![particleextract_2017-apr-03 1](https://cloud.githubusercontent.com/assets/1957186/24599507/30595076-1859-11e7-8b3d-9d70326fdec5.jpg)

**Comment by aaronkennedy** [comment]
¯\_(ツ)_/¯
