### ISSUE TITLE
Simulator window stuck behind macOS menubar

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#514]
I just had the situation where the simulator window was stuck behind the menu bar in such a way that i couldn't move it. Disabling the simulator and re-enabling it did not move the simulator window down to reveal the window's titlebar. The only way i could move it was by enabling the device frame and dragging it down.

![Screen Shot 2019-09-05 at 17 38 29](https://user-images.githubusercontent.com/8209164/64321713-76050d80-d004-11e9-8dc8-78b033bb7c82.png)

**Comment by aaronkennedy** [comment]
I don't think I can do anything about this
