### ISSUE TITLE
Things that should be "fixable" are not

### ISSUE THREAD

**Issue by custa1200** [ZingWorkshop/Studio#541]
The following scenario I was not presented with the nice way to fix it and had to do manually.

<img width="954" alt="Screen Shot 2020-02-11 at 4 59 41 pm" src="https://user-images.githubusercontent.com/161224/74214199-942c1380-4cf0-11ea-9d9b-b9954922cfd4.png">

**Comment by aaronkennedy** [comment]
Can't reproduce
