### ISSUE TITLE
Add refresh button in Zing Preview

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#553]
Right now I'm sharing a prototype with about a dozen people and when I make updates they need to either find the link again or kill zing preview to get it to download the latest version... it would be awesome if there was a refresh button to download the latest version.

**Comment by aaronkennedy** [comment]
Would it just checking each time it started be ok? So as long as they had returned to the homescreen it would see the update

**Comment by aaronkennedy** [comment]
On second thoughts, it should do both - check on start and have a check for updates button so that it behaves just like Studio does.

**Comment by custa1200** [comment]
Would be nice if there was a method we could call by code so we could put a "restart" button in the proto
