### ISSUE TITLE
Allow elements to be pinned to locations on a map

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#57]
For example as shown in these apps:

![airbnb](https://cloud.githubusercontent.com/assets/8209164/24890695/bc001856-1eb4-11e7-9a9e-de8ee5827ccb.png)

![gogobot 6](https://cloud.githubusercontent.com/assets/8209164/24890703/c2751664-1eb4-11e7-9ad8-7708fe1dc40e.png)

![instagram maps](https://cloud.githubusercontent.com/assets/8209164/24890730/e1df1dba-1eb4-11e7-8265-a7b81aec2e19.png)

**Comment by aaronkennedy** [comment]
Out of scope
