### ISSUE TITLE
Right-clicking while dragging causes the simulation to be broken

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#578]
Not sure if this is a real bug or not but I wasn't expecting it to break when I accidentally right-clicked while dragging.

https://www.zingstudio.io/share/ViewTransitions/d90870551c5839243fc58490692a98979f6616228614f17f971fe947b883ae52

**Comment by aaronkennedy** [comment]
Works on Windows. Just sayin' :)
