### ISSUE TITLE
Issue with safe area insets

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#592]
If you view this example in landscape mode on an iPhone X class device the text flickers. The safe area insets aren't being used correctly but the result is not expected.

https://www.zingstudio.io/share/2020-07-04-01/e623adeac45a18c6d798d58ff7923bb683a3bbaa7b94d93dfb2ba38ed275fb3e

**Comment by aaronkennedy** [comment]
This is the "expected" behaviour, and is the reason safe area anchors are preferred as errors like this can be detected.
