### ISSUE TITLE
Not possible to build an app and run on iPhone SE (original)

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#624]
Xcode gives the following error:

dyld: Library not loaded: @rpath/ZingEngine.framework/ZingEngine
  Referenced from: /private/var/containers/Bundle/Application/4AD7A628-1F25-46B0-BB10-4DF8CD960779/MTV.app/MTV
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4AD7A628-1F25-46B0-BB10-4DF8CD960779/MTV.app/Frameworks/ZingEngine.framework/ZingEngine: code signature invalid for '/private/var/containers/Bundle/Application/4AD7A628-1F25-46B0-BB10-4DF8CD960779/MTV.app/Frameworks/ZingEngine.framework/ZingEngine'

	/private/var/containers/Bundle/Application/4AD7A628-1F25-46B0-BB10-4DF8CD960779/MTV.app/Frameworks/ZingEngine.framework/ZingEngine: stat() failed with errno=25
(lldb)

**Comment by aaronkennedy** [comment]
Apparently this is a bug in iOS 13.3 when using a free developer account https://stackoverflow.com/questions/60015309/how-to-run-an-ios-app-that-causes-runtime-error-for-frameworks-code-signature-i
