### ISSUE TITLE
Following project does not animate when it is a live webshare

### ISSUE THREAD

**Issue by NigelBreslaw** [ZingWorkshop/Studio#657]
Just shows a solid color that never changes https://www.zingstudio.io/share/WebTest/cd569bd2b7f8c4de070f9d9a5aa6efd9ea43638c3427446aaa1aae1b83905cf7?live=iPhone8

**Comment by aaronkennedy** [comment]
This is only half a bug. If the Animation.Sequential children take 0ms to run, it wont loop. As WASM builds didn't seed their random generator, the initial durationVariance was always -1000, so the total delay was always 0. This could still happen on desktop, but obviously it was less likely.

Zing will now print an error when the 0ms condition happens, and I've seeded the random number generator so WASM and desktop will behave the same.
