### ISSUE TITLE
Autocomplete doesn't complete casting correctly

### ISSUE THREAD

**Issue by michaelahokas** [ZingWorkshop/Studio#88]
When typing:
    
    property Video test: (videoPreview cast Video)

the keyword "cast" doesn't autocomplete but "Video" does

When typing:

     property Component.LoopingCarousel test: (carousel cast Component.LoopingCarousel)

the keyword "cast" doesn't autocomplete and neither does the element name "Component.LoopingCarousel"

**Comment by KiritC** [comment]
I can second that I'm not getting element autocomplete when finding an element to cast
